# Generated by Django 2.1.5 on 2020-03-31 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cust_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('addressOne', models.TextField(max_length=100)),
                ('addressTwo', models.TextField(blank=True, max_length=100)),
                ('town_city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=6)),
                ('phone', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_username', models.CharField(max_length=255, unique=True)),
                ('merchant_password', models.CharField(max_length=255)),
                ('merchant_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_status', models.CharField(default=1, max_length=1)),
                ('trans_time', models.DateTimeField()),
                ('trans_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('trans_quantity', models.PositiveIntegerField()),
                ('trans_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Merchant')),
                ('trans_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_fb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_tw_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('0', 'customer'), ('1', 'merchant')], max_length=1)),
                ('picture_img_link', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whisky_name', models.CharField(max_length=255)),
                ('whisky_description', models.CharField(max_length=255)),
                ('whisky_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('whisky_quantity', models.PositiveIntegerField(default=1)),
                ('whisky_status', models.IntegerField(default=1)),
                ('whisky_img_link', models.CharField(blank=True, max_length=255)),
                ('whisky_img', models.ImageField(blank=True, upload_to='product_images')),
            ],
            options={
                'verbose_name_plural': 'Whiskies',
            },
        ),
        migrations.CreateModel(
            name='WhiskyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whisky_category_name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='whisky',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WhiskyList'),
        ),
        migrations.AddField(
            model_name='whisky',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whisky',
            name='whisky_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location', to_field='location_name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Whisky'),
        ),
    ]
