# Generated by Django 2.2.10 on 2020-02-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='age',
        ),
    ]
