# Generated by Django 2.2.10 on 2020-03-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tweet_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Customer',
        ),
    ]
