# Generated by Django 2.1.5 on 2020-03-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200328_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisky',
            name='location',
        ),
        migrations.AddField(
            model_name='whisky',
            name='whisky_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Location', to_field='location_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
