# Generated by Django 2.1.5 on 2020-03-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200328_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
