# Generated by Django 2.1.5 on 2020-03-31 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Delivery'),
        ),
    ]
