# Generated by Django 2.1.5 on 2020-03-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200319_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='merchant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Merchant'),
            preserve_default=False,
        ),
    ]
