# Generated by Django 2.1.5 on 2020-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200331_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
