# Generated by Django 2.1.5 on 2020-03-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200328_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whisky',
            options={'verbose_name_plural': 'Whiskies'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture_img_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='whisky_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
