# Generated by Django 3.0.4 on 2020-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200316_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_fb_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
