# Generated by Django 2.1.5 on 2020-03-31 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whisky_category_name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
    ]
