# Generated by Django 2.1.5 on 2020-03-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_whisky_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
