# Generated by Django 2.1.5 on 2020-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200319_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='whisky_status',
            field=models.IntegerField(default=1),
        ),
    ]
