# Generated by Django 2.1.5 on 2020-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200315_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('0', 'customer'), ('1', 'merchant')], max_length=1),
        ),
    ]
