# Generated by Django 3.0.4 on 2020-03-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200316_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_fb_id',
        ),
    ]
