# Generated by Django 3.0.4 on 2020-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200320_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cust_tw_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
