# Generated by Django 2.1.5 on 2020-03-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_cust_fb_id'),
        ('app', '0007_auto_20200315_1921'),
    ]

    operations = [
    ]
